#!/bin/bash

STACK_NAME=devbox

INSTANCE_NAME=$1

if [ -z $INSTANCE_NAME ]; then
  echo "Usage: down <your name of instance>"
  exit 1
fi

# Running instances with tag Application=devbox
INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=$STACK_NAME" "Name=tag:ResourceName,Values=$INSTANCE_NAME" "Name=instance-state-code,Values=16" | jq -r '.Reservations[].Instances[].InstanceId')

RESULT=$(aws --profile devbox ec2 terminate-instances --instance-ids $INSTANCE_ID)
