#!/bin/bash

STACK_NAME=devbox
INSTANCE_NAME=$1

if [ -z $INSTANCE_NAME ]; then
  echo "Usage: stop <your name of instance>"
  exit 1
fi

# Running instances with tag Application=devbox
INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=devbox" "Name=tag:ResourceName,Values=$INSTANCE_NAME" "Name=instance-state-code,Values=16" | jq -r '.Reservations[].Instances[].InstanceId')

if [ -z $INSTANCE_ID ]; then
  echo "Failed: No running instances named '$INSTANCE_NAME'."
  exit 1
fi

if (( $(grep -c . <<<"$INSTANCE_ID") > 1 )); then 
  echo "Failed: Multiple instances running:"
  echo "$INSTANCE_ID"
  exit 1
fi

RESULT=$(aws --profile devbox ec2 stop-instances --instance-ids $INSTANCE_ID)

echo "Stopping $INSTANCE_ID."
