#!/bin/bash

STACK_NAME=devbox

echo "Images:"
#aws --profile devbox ec2 describe-images --filters "Name=tag:Application,Values=$STACK_NAME" | jq -r '.Images[] | "    "+.Name + " (" + .State + ")"'
./images
echo "Instances:"
#aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=$STACK_NAME" | jq -r '.Reservations[].Instances[] | "    "+.InstanceId+" - "+.InstanceType+" ("+.State.Name+")"'
./instances