#!/bin/bash

IMAGE_NAME=$1

if [ -z $IMAGE_NAME ]; then
  echo "Usage: snapshot <image name>"
  exit 1
fi

STACK_NAME=devbox

# Running instances with tag Application=devbox
INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=devbox" "Name=instance-state-code,Values=16" | jq -r '.Reservations[].Instances[].InstanceId')

if (( $(grep -c . <<<"$INSTANCE_ID") > 1 )); then 
  echo "Failed: Multiple instances are running:"
  echo "$INSTANCE_ID"
  exit 1
fi

# Create an AMI from the existing instance (so we can restore it next time)
AMI_ID=$(aws --profile devbox ec2 create-image --instance-id "$INSTANCE_ID" --name "$IMAGE_NAME" | jq -r '.ImageId' )
aws --profile devbox ec2 create-tags --resources $AMI_ID --tags Key=Application,Value=$STACK_NAME

echo "Creating image $IMAGE_NAME from instance $INSTANCE_ID with AMI ID $AMI_ID"
