#!/bin/bash

STACK_NAME=devbox
INSTANCE_NAME=$1

if [ -z $INSTANCE_NAME ]; then
  echo "Usage: start <your name of instance>"
  exit 1
fi

# Running instances with tag Application=devbox
INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=devbox" "Name=tag:ResourceName,Values=$INSTANCE_NAME" "Name=instance-state-code,Values=80" | jq -r '.Reservations[].Instances[].InstanceId')

if [ -z $INSTANCE_ID ]; then
  echo "Failed: No stopped instances named '$INSTANCE_NAME'."
  exit 1
fi

if (( $(grep -c . <<<"$INSTANCE_ID") > 1 )); then 
  echo "Failed: Multiple instances running:"
  echo "$INSTANCE_ID"
  exit 1
fi

RESULT=$(aws --profile devbox ec2 start-instances --instance-ids $INSTANCE_ID)

aws --profile $STACK_NAME ec2 wait instance-running --instance-ids $INSTANCE_ID

IP_ADDRESS=$(aws --profile devbox ec2 describe-instances --instance-ids $INSTANCE_ID | jq -r .Reservations[].Instances[].PublicIpAddress)

echo "Instance $INSTANCE_ID running on $IP_ADDRESS"
