#!/bin/bash

STACK_NAME=devbox

# Running instances with tag Application=devbox
INSTANCE_ID=$(aws --profile devbox ec2 describe-instances --filters "Name=tag:Application,Values=devbox" "Name=instance-state-code,Values=16" | jq -r '.Reservations[].Instances[].InstanceId')

if (( $(grep -c . <<<"$INSTANCE_ID") > 1 )); then 
  echo "Failed: Multiple instances running:"
  echo "$INSTANCE_ID"
  exit 1
fi

RESULT=$(aws --profile devbox ec2 stop-instances --instance-ids $INSTANCE_ID)

echo "Stopping $INSTANCE_ID."
